### PR TITLE
Update DESCRIPTION

### PR DESCRIPTION
**Pull request by Robinlovelace**
Good to go when https://github.com/Nowosad/spDataLarge/pull/21#issuecomment-657229740 is merged I think. Heads-up @Nowosad, we're getting towards a stable build!

### CODE REVIEW

**Comment by Nowosad** [comment]
Nice. One question - why we are using the dev version of bookdown?

**Comment by Robinlovelace** [comment]
> why we are using the dev version of bookdown?

Not 100% sure. I'm happy to use master. I think it may have been related to https://github.com/Robinlovelace/geocompr/issues/500

**Comment by Nowosad** [comment]
I think we can use the master version. Can you change that?

**Comment by Robinlovelace** [comment]
> Can you change that?

Sure. Job done.

**Comment by Robinlovelace** [comment]
It would be good for the book to build completely with CRAN packages but that's for another day...

**Comment by Nowosad** [comment]
@Robinlovelace - https://github.com/geocompr/geocompkg/runs/881351939?check_suite_focus=true - we need to update the solutions vignettes...

**Comment by Robinlovelace** [comment]
OK I'll open an issue.

**Pull request merged**
