### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by jannes-m** [comment]
I have added a few missing packages and hope that I haven't forgotten one but we will find out soon enough, I guess or maybe not since all the ml stuff is handled with `eval=FALSE` to avoid super-long computation times in the CI.

**Review by jannes-m — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Thanks @jannes-m I'm seeing this issue in the CI: 

```
Error: Error: Missing commas separating Remotes: 'mlr-org/mlr3extralearners
```

Looks like my earlier commits were also failing...

**Comment by jannes-m** [comment]
Sorry, forgetting the commas was my bad. This is fixed. One reason why the book won't built is that the solutions of c14 (now c15) cannot be compiled. This is because we have deleted the old mlr deps from the DESCRIPTION.

**Comment by Nowosad** [comment]
Hi @jannes-m -- please also update the package version and then I think it is ready for the merge

**Pull request merged**
