### PR TITLE
Install stars

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
I noticed on docker that these potentially useful packages are not installed by default. Worth adding them IMO.

**Comment by Nowosad** [comment]
Should it have more packages that we have in the book? Isn't that just make its installation longer (inconvenience to users)?

**Comment by Robinlovelace** [comment]
I think the advantages of having stars and other packages in there any possible downsides of increased install time. But maybe I've missed something. More immediately, it will all me to use the geocompr docker image more in my teaching/research!

**Comment by Nowosad** [comment]
@Robinlovelace feel free to merge this pull request if it is useful for you;)

**Comment by Robinlovelace** [comment]
Job done - good to get some discussion on it 1st.

**Pull request merged**
